### ISSUE TITLE
id not allowed in requestbody for date/location/person annotator, but id is part of the returned clinical notes

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks/nlp-sandbox-schemas#92]
<img width="1424" alt="Screen Shot 2020-11-23 at 3 43 42 PM" src="https://user-images.githubusercontent.com/10556275/99938471-d1a2ee80-2da2-11eb-94d7-44eb55bfdcd8.png">

Did you want me to remove "id" from each clinical note prior to calling the restPOST?

The rest call works if I remove the "id" from the request body.

**Comment by tschaffter** [comment]
Do you remember when I mentioned that I was considering creating two schemas to solve the issue where a property should be part of the input and not the output or vice versa? OpenAPI options `readOnly` and `writeOnly` intend to solve this problem in a DRY way.

The problem that you report is actually due to connexion-Flask not respecting the option `readOnly` and `writeOnly` when generating examples of request bodies. Here `id` is marked as `readOnly` and so should only be included in output objects. You can confirm this by looking at the schema of the request body.

![image](https://user-images.githubusercontent.com/3056480/99988918-e82b5480-2d66-11eb-9735-a79faf1de8f6.png)

Here is what OpenApi doc says:

> Relevant only for Schema "properties" definitions.  Declares the property as "read only". This means that it MAY be sent as  part of a response but SHOULD NOT be sent as part of the request. If the  property is marked as readOnly being true and is in the required list, the required will take effect on the response only. A property MUST NOT be marked as both readOnly and writeOnly being true. Default value is false.

Note the use of "SHOULD NOT" and not "MUST NOT" in "SHOULD NOT be sent as part of the request". This means that connexion-Flask should not throw an error if a property marked as `readOnly` is included in the request body.

See https://github.com/nlpsandbox/data-node/issues/81

Open discussion in `connexion` project:
https://github.com/zalando/connexion/issues/942
https://github.com/zalando/connexion/issues/350

The solution described [here](https://github.com/zalando/connexion/issues/942#issuecomment-575134140) as part of 942 complicates the code too much and I don't want this to confuse our developers since we provide this code as example.

**Comment by tschaffter** [comment]
Open tickets for OpenAPITools/openapi-generator:
https://github.com/OpenAPITools/openapi-generator/issues/4190

**Comment by thomasyu888** [comment]
The resolution is that 'id' needs to be removed from clinical notes prior to annotation.
